### ISSUE TITLE
On day checklist

### ISSUE THREAD

**Issue by BeastyBlacksmith** [julia-users-berlin/julia-users-workshop#6]
- [ ] Print signposts
- [ ] Test the beamer
- [ ] Run through all the slides
- [ ] update demo computer
- [ ] run through all live material
Check for:
- [ ] Name tags
- [ ] Post-its
- [ ] Pens
- [ ] Connecter to beamer (VGA & HDMI)

Did I forget something?

**Comment by daveh19** [comment]
Probably need adapters to connect to the projector.
